using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Runtime.InteropServices;
using System.Text;
using Entitas;
using Ent = GenEntitas.MainEntity;

namespace GenEntitas
{
	[Export(typeof(ISystem))]
	[Guid("93E843A5-D1F0-4F8E-825C-D5627635ADF7")]
	public class PostProcAddFileHeaderSystem : ReactiveSystem<Ent>
	{
		public				PostProcAddFileHeaderSystem				(  ) : this( Contexts.sharedInstance )
		{
		}

		public				PostProcAddFileHeaderSystem				( Contexts contexts ) : base( contexts.main )
		{
		}

		private const		String					TEMPLATE				=
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ${GeneratedBy}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		protected override	ICollector<Ent>			GetTrigger				( IContext<Ent> context )
		{
			return context.CreateCollector( MainMatcher.GeneratedFileComp );
		}

		protected override	Boolean					Filter					( Ent entity )
		{
			return entity.hasGeneratedFileComp;
		}

		protected override	void					Execute					( List<Ent> entities )
		{
			foreach ( var ent in entities )
			{
				var stringBuilder = new StringBuilder( TEMPLATE.Replace("${GeneratedBy}", ent.generatedFileComp.GeneratedBy) );
				stringBuilder.Append( ent.generatedFileComp.Contents );
				ent.ReplaceGeneratedFileComp(
					ent.generatedFileComp.FilePath,
					stringBuilder.ToString(  ),
					ent.generatedFileComp.GeneratedBy );
			}
		}
	}
}