using System;
using System.Collections.Generic;
using System.Text;
using Entitas;
using Ent = MainEntity;

namespace GenEntitas.Sources
{
	public class PostProcAddFileHeaderSystem : ReactiveSystem<Ent>
	{
		public				PostProcAddFileHeaderSystem				( Contexts contexts ) : base( contexts.main )
		{
			_contexts			= contexts;
		}

		private				Contexts				_contexts;
		private const		String					TEMPLATE				=
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ${GeneratedBy}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		protected override	ICollector<Ent>			GetTrigger				( IContext<Ent> context )
		{
			return context.CreateCollector( MainMatcher.GeneratedFileComp );
		}

		protected override	Boolean					Filter					( Ent entity )
		{
			return entity.hasGeneratedFileComp;
		}

		protected override	void					Execute					( List<Ent> entities )
		{
			foreach ( var ent in entities )
			{
				var stringBuilder = new StringBuilder( TEMPLATE.Replace("${GeneratedBy}", ent.generatedFileComp.GeneratedBy) );
				stringBuilder.Append( ent.generatedFileComp.Contents );
				ent.ReplaceGeneratedFileComp(
					ent.generatedFileComp.FilePath,
					stringBuilder.ToString(  ),
					ent.generatedFileComp.GeneratedBy );
			}
		}
	}
}